import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const root = process.cwd();
const sourcePath = join(root, "design", "tokens", "hcmus.tokens.json");
const cssPath = join(root, "app", "design-tokens.css");
const tsPath = join(root, "lib", "design-tokens", "tokens.ts");

function kebab(value) {
  return value.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function flattenTokens(node, path = []) {
  return Object.entries(node).flatMap(([key, value]) => {
    if (value && typeof value === "object" && "value" in value) {
      return [[path.concat(key).map(kebab).join("-"), value.value]];
    }

    return flattenTokens(value, path.concat(key));
  });
}

const tokens = JSON.parse(readFileSync(sourcePath, "utf8"));
const flatTokens = flattenTokens(tokens);
const css = [
  "/* Generated by scripts/build_design_tokens.mjs. Edit design/tokens/hcmus.tokens.json instead. */",
  ":root {",
  ...flatTokens.map(([name, value]) => `  --${name}: ${value};`),
  "}",
  "",
].join("\n");
const ts = [
  "/* Generated by scripts/build_design_tokens.mjs. Edit design/tokens/hcmus.tokens.json instead. */",
  "\n",
  "export const designTokens = ",
  JSON.stringify(tokens, null, 2),
  " as const;",
  "",
].join("");

mkdirSync(dirname(tsPath), { recursive: true });
writeFileSync(cssPath, css);
writeFileSync(tsPath, ts);

console.log(`Generated ${cssPath}`);
console.log(`Generated ${tsPath}`);
